### ISSUE TITLE
pushgateway publisher fails when module name contains "-" 

### ISSUE THREAD

**Issue by vipsy** [cdsap/Talaiot#106]
When adding a module named `test-module` to an app, it fails to parse the data properly.

```
[SimpleRequest]: send request to http://localhost:9091/metrics/job/task
[SimpleRequest]: Response code 400
[SimpleRequest]: Response code not Successful
[SimpleRequest]: Message Response Bad Request
[SimpleRequest]: Response Body text format parsing error in line 12: expected float as value, got "-module:generateDebugBuildConfig{state=\"UP_TO_DATE\",module=\":test-module\",rootNode=\"false\""
```

it can send `build` metrics but fails in `task` metrics.

**Comment by cdsap** [comment]
thanks again for the report. 
I see the problem with the module name containing `-`. The label for the metric doesn't allow the character. 
I published a hotfix replacing the characters for `_`.  Version 1.0.6 available now
Now the label would be:
`:test_module:assemble`
You can check #107

**Comment by vipsy** [comment]
my problem got resolved using 1.0.6 and I could get it to publish to Prometheus.
anything else you noticed as you re-opened the issue?

**Comment by cdsap** [comment]
Accidentally I closed the issue, that's why I reopened.
Anyways I can close it?

**Comment by cdsap** [comment]
Hi @vipsy 
can I close these issues?

**Comment by vipsy** [comment]
Yes it’s good now. Please close.

**Comment by cdsap** [comment]
solved
