### ISSUE TITLE
git metrics are not being populated

### ISSUE THREAD

**Issue by vipsy** [cdsap/Talaiot#114]
when you add     
   ` metrics {
        git() 
}`
It should populate git branch and username into metrics.
But they are not being populated.

**Comment by cdsap** [comment]
thanks for the report, I will check it

**Comment by cdsap** [comment]
Fixed and merged, available as snapshot. 
Sorry for the delay, I was moving to another country. 
Let me know if it works for you.

**Comment by cdsap** [comment]
@vipsy have you tried? Can I close this issue?

**Comment by vipsy** [comment]
Hi, I am yet to try the new version but you can close if it's working. I will integrate it later.

It must be very exciting to move to a new country. 
Cheers.

**Comment by cdsap** [comment]
Hi @vipsy I'm closing this issue as I don't reproduce it anymore, in case it still happening for you we can reopen
