### ISSUE TITLE
Default Grafana change

### ISSUE THREAD

**Issue by emartynov** [cdsap/Talaiot#118]
Question: Is it possible and would it be handy to modify dashboard/graphs to see any task from gradle build run?

It is nice to see graphs for the requested tasks. But would be great also to see other tasks graphs.

**Comment by cdsap** [comment]
Hi @emartynov, 
If you are using the plugin with `InfluxdbPublisher` and you have a conf like:
```
talaiot {
    publishers {
        influxDbPublisher {
            dbName = "tracking"
            url = "http://localhost:8086"
            taskMetricName = "task"
            buildMetricName = "build"
        }
    }
}
```
the tasks are being recorded. 


In the Dashboard used by default we are considering only the builds data. But it doesn't mean we don't have the tasks. 
The entryPoint is called "task" or the value included in the `taskMetricName`. If you create a new graph you can select the "task" table and you will see the tasks recorded:
<img width="677" alt="Screen Shot 2019-10-15 at 6 35 43 PM" src="https://user-images.githubusercontent.com/475733/66881145-b4cea180-ef7a-11e9-91e6-bdd004f10269.png">

Or if you prefer you can play with the queries like:
```
SELECT mean("value") FROM "rpTalaiot"."task" WHERE ("task" = ':core:kaptDebugKotlin') AND $timeFilter GROUP BY time($__interval) fill(null)
```

Let me know if you need more help or you have suggestions

**Comment by emartynov** [comment]
@cdsap Appreciate it!

Yesterday I installed the command-line tool and were able to explore data in the database.
It is just a matter of time to learn the Grafana and database matching.

Thank you for the great tool. I'm going to speak on the local meetup about it.

**Comment by cdsap** [comment]
Thanks @emartynov let me know if you need anything!
