### ISSUE TITLE
Plugin was not found (KTS)

### ISSUE THREAD

**Issue by p-agapov** [cdsap/Talaiot#119]
Got this stack trace:
![2](https://user-images.githubusercontent.com/16005613/67223934-df1bd580-f438-11e9-8e3a-8a53eb528f91.png)
build.gradle.kts:
![1](https://user-images.githubusercontent.com/16005613/67223926-da572180-f438-11e9-9563-45e03a483355.png)

If specify the plugin version:
![image](https://user-images.githubusercontent.com/16005613/67224470-f0b1ad00-f439-11e9-8b17-5ed3348a4ec8.png)
Stack trace:
![image](https://user-images.githubusercontent.com/16005613/67224540-163eb680-f43a-11e9-8a5c-72036b3d44aa.png)

**Comment by tinder-inakivillar** [comment]
hi @p-agapov, thank you very much for the report. 
You're right, the plugin is not applying correctly when we are using kts. I tried to do the same with groovy and it works ok. This pushes me to think about how Gradle is including in the classpath the kts compiled files. 
I used previously Talaiot with kts and I can share some alternatives:
1- Include the plugin in the main entry module of the app conf(It would be included only once)
2- Apply on the main gradle kts file something like:
```
apply(from = "talaiot.gradle.kts)
```
and then there conf the buildscipt and plugin:
```
buildscript {
    repositories {
        mavenCentral()
        google()
    }
    dependencies {
        classpath("com.cdsap:talaiot:1.0.7")
    }
}

apply<com.cdsap.talaiot.TalaiotPlugin>()

configure<com.cdsap.talaiot.TalaiotExtension>() {
    logger = com.cdsap.talaiot.logger.LogTracker.Mode.INFO
    metrics {
        customBuildMetrics("experiment" to  "$id")
        customTaskMetrics("experiment" to  "$id")
    }
    publishers {

        influxDbPublisher {
            dbName = "tracking"
            url = "http://bagan-influxdb.default:8086"
            taskMetricName = "tasks"
            buildMetricName = "build"
        }
    }
}
```
3- Apply the resolution of the plugin in the settings.gradle.kts:
```
pluginManagement({
    repositories {
        mavenCentral()
    }
    resolutionStrategy {
        eachPlugin {
            when (requested.id.id) {
                "talaiot"->{
                    useModule("com.cdsap:talaiot:1.0.7")
                }
            }
        }
    }
})
```
You can include Talaiot in the main gradle file without problem:
```
plugins {
        id("talaiot")
}
```

Let me know if any of these solutions work for you.

**Comment by cdsap** [comment]
hi @p-agapov 
after updating to Gradle 6 and deploying to plugin portal this issue should be solved
