### ISSUE TITLE
Check compatibility with Gradle 6.0

### ISSUE THREAD

**Issue by cdsap** [cdsap/Talaiot#120]

**Comment by emartynov** [comment]
Is it still open? I think we recently lost our stats publishing to influx db. We upgraded to Gradle 6.0 and gradle enterprise plugin 3.0.

**Comment by cdsap** [comment]
Hi @emartynov 
PR was created https://github.com/cdsap/Talaiot/pull/124/files and need to run more integration tests before merging. 
What was the reason for:
`I think we recently lost our stats publishing to influx db.` ?
How you were running InfluxDb instance?

**Comment by cdsap** [comment]
done and merged in the last release. Closing this issue
