### ISSUE TITLE
Unable to load sample data

### ISSUE THREAD

**Issue by ipereziriarte** [cdsap/Talaiot#128]
I'm trying to populate the influxdb with sample data, following the docker sample steps.

After installing the docker image, etc I built the sample project and run
`bash scripts/populate.sh`

On the first run, I faced the issue:
```
Caused by: org.gradle.api.plugins.UnknownPluginException: Plugin [id: 'talaiot', version: '1.0.8-SNAPSHOT', artifact: 'com.cdsap:talaiot:1.0.8-SNAPSHOT'] was not found in any of the following sources:
- Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/5.1/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (could not resolve plugin artifact 'com.cdsap:talaiot:1.0.8-SNAPSHOT')
  Searched in the following repositories:
    maven(file:/Users/imanol/projects/Talaiot/build/repository/)
    maven2(https://plugins.gradle.org/m2/)
	at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.resolveToFoundResult(DefaultPluginRequestApplicator.java:262)
	... 133 more
```
That I fixed by changing the dependencies in the sample project:
![Screenshot 2019-11-26 at 11 02 09](https://user-images.githubusercontent.com/1949825/69623114-8bf1ff80-1042-11ea-878e-573cd273b1de.png)

Next run, it finished:
<img width="723" alt="success" src="https://user-images.githubusercontent.com/1949825/69623394-1aff1780-1043-11ea-9c71-4f5cf43e702e.png">

However, the graphana dashboard is empty:
![Screenshot 2019-11-26 at 11 58 12](https://user-images.githubusercontent.com/1949825/69623975-11c27a80-1044-11ea-875c-ac65c05b2cc1.png)

If I query the database directly, looks like it's empty too:
```
curl -G 'http://localhost:8086/query?pretty=true' --data-urlencode "db=tracking" --data-urlencode "q=SELECT \"value\", \"task\" FROM \"tracking\""
{
    "results": [
        {
            "statement_id": 0
        }
    ]
}
```

Is there any step I'm missing?

Thanks in advance 👍

**Comment by ipereziriarte** [comment]
After more investigation I found this error
```
[InfluxDbPublisher]: InfluxDbPublisher-Error-Executor Runnable: retention policy not found: rpTalaiot
```

I managed to fix the sample editing the sample `build.gradle.kts` file and adding the following:

```
retentionPolicyConfiguration {
                name = "autogen"
                duration = "4w"
                shardDuration = "30m"
                replicationFactor = 1
                isDefault = true
            }
```

**Comment by cdsap** [comment]
@ipereziriarte thank you very much for the report.
the issue with the sample is fixed in the #129 
Regarding the second issue with the Retention policy, we had previously problems with the same issue, the original problems comes from:
https://github.com/influxdata/influxdb-java/issues/373
 I will revisit again this issue and try to give better solution.

**Comment by cdsap** [comment]
regarding the problem of the retention policy, is fixed here:
https://github.com/cdsap/Talaiot/pull/130

Problem was we were creating the database in the Docker image. 
Docker image pushed and tested ok. 

Thanks for the report

**Comment by ipereziriarte** [comment]
Thanks for the quick response @cdsap 👍

**Comment by cdsap** [comment]
Hi @ipereziriarte can I close this issue?

**Comment by ipereziriarte** [comment]
Yes sure!
