### ISSUE TITLE
Docker Hub Deployment

### ISSUE THREAD

**Issue by cdsap** [cdsap/Talaiot#13]
There is not possible to deploy with docker.hub due an error with the paths 

```
Step 18/31 : COPY supervisord/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY failed: stat /var/lib/docker/tmp/docker-builder097208477/supervisord/supervisord.conf: no such file or directory
```

**Comment by Malinskiy** [comment]
@cdsap how did you specify the Dockefile path in the docker hub?

**Comment by Malinskiy** [comment]
This issue probably is because you're specifying something like this:
```bash
docker build -t test -f docker/Dockerfile .
```

when you should specify the following

```bash
docker build -t test -f docker/Dockerfile docker
```

**Comment by cdsap** [comment]
@Malinskiy thank you. 
I saw the problem was in the path of the build context with `/`.
Now is ok with:
<img width="1070" alt="screen shot 2019-02-19 at 17 46 41" src="https://user-images.githubusercontent.com/475733/53009598-78d85080-346e-11e9-9be0-c5f706760bd6.png">

**Comment by cdsap** [comment]
Fixed

<img width="1074" alt="screen shot 2019-02-19 at 17 48 53" src="https://user-images.githubusercontent.com/475733/53009697-a6bd9500-346e-11e9-8375-d24a2034f8a2.png">
