### ISSUE TITLE
influxDbPublisher doesn't send data when "--no-daemon" is present

### ISSUE THREAD

**Issue by MyDogTom** [cdsap/Talaiot#131]
I noticed that when Gradle task is executed with `--no-daemon` data doesn't reach InfluxDB. In the log I still see
```
[InfluxDbPublisher]: ================
[InfluxDbPublisher]: InfluxDbPublisher
[InfluxDbPublisher]: publishBuildMetrics: true
[InfluxDbPublisher]: publishTaskMetrics: true
[InfluxDbPublisher]: ================
```
but data is absent.

Is that expected behavior?

**Comment by tinder-inakivillar** [comment]
hi @MyDogTom 
thank you very much for the report, I have found a bug using the executor service.
I will work on a new update, I'm considering using coroutines but I need to double-check everything is ok

**Comment by snpefk** [comment]
Bug is still present in version 1.5.1. 
Have the same logs
```
[InfluxDbPublisher]: ================
[InfluxDbPublisher]: InfluxDbPublisher
[InfluxDbPublisher]: publishBuildMetrics: true
[InfluxDbPublisher]: publishTaskMetrics: true
[InfluxDbPublisher]: ================
```
