### ISSUE TITLE
Gradle tasks abbreviation and "requestedTask"

### ISSUE THREAD

**Issue by MyDogTom** [cdsap/Talaiot#132]
Gradle supports [task abbreviation](https://docs.gradle.org/current/userguide/command_line_interface.html#task_name_abbreviation)
>When you specify tasks on the command-line, you don’t have to provide the full name of the task. You only need to provide enough of the task name to uniquely identify the task. 

For example, I can execute:
`gradle assembleDebug`
`gradle assDeb`
`gradle aD`

All these are the same task, but they will be reported differently in `build.requestedTask`.

I wonder is that possible to always detect a full name for `requestedTask`? This would simplify analysis like "How `app:assembleDebug` task changes overtime".

**Comment by tinder-inakivillar** [comment]
hi @MyDogTom 
thanks again for the report. You're right we need to support task abbreviation

**Comment by MyDogTom** [comment]
There is one very similar use case. Both `:app:assembleDebug` and `app:assembleDebug` are the same task.
