### ISSUE TITLE
Should "task breakdown" dashboard include only tasks with `rootNode = false`?

### ISSUE THREAD

**Issue by MyDogTom** [cdsap/Talaiot#133]
`rootNode` documentation says 
>In case we are executing a general task like assembleDebug, the length of the execution is not tracked, Talaiot aggregates the execution of the different tasks and need to inform that a given task it was invoke as main task to execute

As I understand that, if task has `rootNode = true` , then duration (`value`) includes duration of all other tasks. In that case "Task breakdown" dashboard should include only tasks with `rootNode = false`.

Do I understand it correctly?
If yes, then I suggest to change current query
```sql
SELECT sum("value") FROM "$db"."$rp"."task" WHERE $timeFilter GROUP BY state,time($__interval) fill(null)
```

to 

```sql
SELECT sum("value") FROM "$db"."$rp"."task" WHERE $timeFilter AND "rootNode" = 'false' GROUP BY state,time($__interval) fill(null)
```

**Comment by cdsap** [comment]
happy new year @MyDogTom 
I checked the dashboard panel and you're completely right.
Changed, pushed last image in Docker Hub and PR created! 
Thanks
