### ISSUE TITLE
Documentation about custom publisher is outdated

### ISSUE THREAD

**Issue by ipereziriarte** [cdsap/Talaiot#138]
Hi,

I'm on the process of writing a custom publisher for the internal use of my team. And I found quite confusing the mismatch between the wiki, the docs page and the actual values.

### ISSUE

 I realized that the documentation in this [link](https://github.com/cdsap/Talaiot/wiki/Publishers#custompublisher) refers to:

```
interface Publisher {
   fun publish(measurementAggregated: TaskMeasurementAggregated)
}
```
Where `TaskMesasurementAggregated` contains all the aggregated metrics.

However, when I'm implementing the `Publisher` interface I get the following
```
class DummyPublisher(private val config: DummyPublisherConfiguration) : com.cdsap.talaiot.publisher.Publisher {

    override fun publish(report: ExecutionReport) {
       
    }
}
```

Where `ExecutionReport` contains the metrics, configuration data, etc as explained here
in the [docs page](https://cdsap.github.io/Talaiot/com/cdsap/talaiot/entities/ExecutionReport/)

### EXPECTED
Documentation should be updated to match the actual values.
It would also be nice to explain how to create a custom configuration for the custom publisher.

**Comment by cdsap** [comment]
Hi, thank you very much for the issue. 
Doc Publishers has been updated and contains the current way to create new publishers. 

https://github.com/cdsap/Talaiot/wiki/Publishers#custompublisher

**Comment by ipereziriarte** [comment]
Thanks @cdsap I'm going to close the issue :)
