### ISSUE TITLE
Feature request: Add filter option for build

### ISSUE THREAD

**Issue by MyDogTom** [cdsap/Talaiot#141]
As I understand existing `filter` configuration influences only tasks. In my case I'd like to publish data only if `requestedTasks = ":app:assembleDebug"` and build was successful. As far as I see, it's not possible to achieve. Please correct me if I'm wrong.

I propose to enhance `filter` configuration and have something like
```groovy
filter {
    build {
        requestedTasks {
            include = [...]
            exclude = [...]
        }
        success = true
    }
}
```

I'd love to try implement that if you are open for such contribution.

**Comment by cdsap** [comment]
I thinks is a very good feature. Feel free to contribute :)

**Comment by cdsap** [comment]
done by @MyDogTom 
thanks
