### ISSUE TITLE
Unable to find plugin

### ISSUE THREAD

**Issue by bellini-ea** [cdsap/Talaiot#150]
I've added `id("talaiot") version "1.1.0"` to my build.gradle.kts but I'm getting the following.  Happens with or without specifying the version number in the id() declaration.

```* What went wrong:
Plugin [id: 'talaiot', version: '1.1.0'] was not found in any of the following sources:

- Gradle Core Plugins (not a core plugin, please see https://docs.gradle.org/6.2.2/userguide/standard_plugins.html for available core plugins)
- Plugin Repositories (could not resolve plugin artifact 'talaiot:talaiot.gradle.plugin:1.1.0')
  Searched in the following repositories:
    Gradle Central Plugin Repository`

build.gradle.kts (simple test app)

![2020-03-06_21-54-56](https://user-images.githubusercontent.com/46908694/76137942-4789de80-5ff7-11ea-9070-327e18c79ceb.png)

`version = "0.1.0"

plugins {
    java
    application

    // For build metrics
    id("talaiot")
}


repositories {
    mavenLocal()
    mavenCentral()
    jcenter()
}

dependencies {
    classpath("com.cdsap:talaiot:1.1.0")
    implementation("com.google.guava:guava:27.1-jre")
    testImplementation("junit:junit:4.12")
}

apply(plugin = "com.cdsap:talaiot")

application {
    mainClassName = "demo.App"
}

tasks {
    jar {
        manifest {
            attributes(
                mapOf("Implementation-Title" to project.name,
                      "Implementation-Version" to project.version)
            )
        }
    }
}
`

**Comment by bellini-ea** [comment]
I got it to work by adding the resolution strategy to the settings.gradle.kts file.  I followed the sample in the repo.  Maybe the readme should mention that?  I also did not have to add the classpath.

`version = "0.1.0"

repositories {
    mavenLocal()
    mavenCentral()
    jcenter()
}

plugins {
    java
    application

    id("talaiot") version "1.1.0"
}

dependencies {
    implementation("com.google.guava:guava:27.1-jre")
    testImplementation("junit:junit:4.12")
}

apply(plugin = "talaiot")

**Comment by cdsap** [comment]
Hi @bellini-ea, thank you very much for the report.
Indeed, you're right and the configuration under kts requires a workaround.  We have plans to push the plugin to Gradle Portal(actually it's only in bintray) and this will help in setup properly the configuration. 
We have plans to do it ASAP.
