### ISSUE TITLE
Dashboard in readme does not exist

### ISSUE THREAD

**Issue by bellini-ea** [cdsap/Talaiot#151]
In the populating data section, it talks about using the docker image get grafana going.  I got the image going and grafana up however the reference to the dashboard doesn't show up:
`
If you access to the provisioned Dashboard included in the Docker Image(http://localhost:3003/d/F9jppxQiz/android-task-tracking?orgId=1), you will see an empty dashboard like:`

**Comment by cdsap** [comment]
Checking... Thanks for the report

**Comment by cdsap** [comment]
Hi again @bellini-ea, I repeated the process and it worked:
1- I executed:
```
docker run -d \
>   -p 3003:3003 \
>   -p 3004:8083 \
>   -p 8086:8086 \
>   -p 22022:22 \
>   -v /var/lib/influxdb \
>   -v /var/lib/grafana \
>   cdsap/talaiot:latest
```
2- I checked the Dashboard http://localhost:3003/d/F9jppxQiz/talaiot?orgId=1:
<img width="1238" alt="Screenshot 2020-03-07 at 18 43 35" src="https://user-images.githubusercontent.com/475733/76155650-98efa780-60a3-11ea-9e2c-d4e8887cbdb2.png">

3- I executed:
```
bash scripts/populate.sh
```
4- I saw the results populating the dashboard:
<img width="1220" alt="Screenshot 2020-03-07 at 18 41 51" src="https://user-images.githubusercontent.com/475733/76155659-b3298580-60a3-11ea-82ea-0436d7db721f.png">

If it is not working for you, let check first if the docker image is running with `docker ps`:
<img width="585" alt="Screenshot 2020-03-07 at 18 45 55" src="https://user-images.githubusercontent.com/475733/76155673-eff57c80-60a3-11ea-8d6c-c4b072562793.png">

Please let me know and let's check if can work for you.

Thanks

**Comment by bellini-ea** [comment]
Hi.  Thanks very much for your time.  Below are what I get.  I have not run the populate.sh however since I have my own data going to influx. 

![image](https://user-images.githubusercontent.com/46908694/76155757-84141380-60a5-11ea-8ad0-d6784788ea20.png)

![image](https://user-images.githubusercontent.com/46908694/76155760-94c48980-60a5-11ea-8923-c77496a4c2b0.png)

**Comment by cdsap** [comment]
Got it, 
I see you're using a different Docker image. The example in the README is intended to use with the Talaliot Docker image.
But no problem, you can import the dashboard:
https://github.com/cdsap/Talaiot/blob/master/docker/grafana/dashboards/talaiot.json
And create in Grafana the dataset for InfluxDb with*:

<img width="741" alt="Screenshot 2020-03-07 at 19 06 42" src="https://user-images.githubusercontent.com/475733/76155855-f46f6480-60a6-11ea-8118-e97762366ef9.png">

* you can use the credentials required by your local instance

**Comment by bellini-ea** [comment]
I see!  The way I read the readme I had to go to get the image from philhawthorne/docker.... but you have in your repo here!  I used that it works fine!  Thanks for clarifying.
