### ISSUE TITLE
Question: HostnameMetric is not used, why?

### ISSUE THREAD

**Issue by mokkun** [cdsap/Talaiot#154]
Hi,
I've noticed that the `SimpleMetrics.kt` file contains a [`HostnameMetric` class](https://github.com/cdsap/Talaiot/blob/b0e532ae76e31c40fc6e931da76a72238e732290/talaiot/src/main/kotlin/com/cdsap/talaiot/metrics/SimpleMetrics.kt#L82) and that it is not used. 
I was actually implementing my own hostname metric since I didn't see it in the JSON generated report.

Then I notice that it [is already available in the `environment` property](https://github.com/cdsap/Talaiot/blob/b0e532ae76e31c40fc6e931da76a72238e732290/talaiot/src/main/kotlin/com/cdsap/talaiot/entities/ExecutionReport.kt#L109) of the [`ExecutionReport` data class](https://github.com/cdsap/Talaiot/blob/b0e532ae76e31c40fc6e931da76a72238e732290/talaiot/src/main/kotlin/com/cdsap/talaiot/entities/ExecutionReport.kt#L4). But the `HostnameMetric` [is never written](https://github.com/cdsap/Talaiot/blob/b0e532ae76e31c40fc6e931da76a72238e732290/talaiot/src/main/kotlin/com/cdsap/talaiot/configuration/MetricsConfiguration.kt#L41) into it. Why is that?

Also, the current implementation [sets its value](https://github.com/cdsap/Talaiot/blob/b0e532ae76e31c40fc6e931da76a72238e732290/talaiot/src/main/kotlin/com/cdsap/talaiot/metrics/SimpleMetrics.kt#L83) as `SystemInfo().operatingSystem.manufacturer`, which is odd.

**Comment by cdsap** [comment]
Hi @mokkun thank you very much for the report. 
You're right. I'm going to check it and create PR

**Comment by mokkun** [comment]
Thanks for the great work. Let me know if I can help, either with creating a PR or reviewing it. 👍

**Comment by cdsap** [comment]
hi @mokkun 
PR created https://github.com/cdsap/Talaiot/pull/157 please let me know what do you think

**Comment by mokkun** [comment]
Great, thanks. I will check it now. :+1:

**Comment by mokkun** [comment]
Will take the liberty and close this, since it is solved by #157.
