### ISSUE TITLE
Question: adding custom Metric into configuration

### ISSUE THREAD

**Issue by mokkun** [cdsap/Talaiot#155]
I'm playing around with custom metrics and read the bits about [Extending custom metrics](https://github.com/cdsap/Talaiot/wiki/Metrics#extending--custom-metrics). I've done the following and it works fine (Groovy):

```groovy
talaiot {
    metrics {
        customBuildMetrics([myMetric: "Hello world"])
    }
    publishers {
        customPublisher(new CustomPublisher())
    }
}
```

But it would be interesting to have a method that takes a `Metric` and adds it into the `MetricsConfiguration.metrics` list.

```groovy
talaiot {
    metrics {
        customMetrics(new MyCustomMetric())
    }
    publishers {
        customPublisher(new CustomPublisher())
    }
}
```

This would allow us to:

1. Have only custom metrics reported.
2. Override any existing metrics. e.g. add an extension of GitMetrics with more data.
3. Have our metrics organized in a package and in their own file(s).

Does it make sense to have such a feature added to the API?

P.S.: the docs seem to be outdated. e.g. `gitMetrics = false` does not work for me.

**Comment by MyDogTom** [comment]
It's already possible. Such

**Comment by MyDogTom** [comment]
It's already possible. Such config looks like
```Groovy
import com.cdsap.talaiot.metrics.GitBranchMetric
import com.github.mydogtom.talaiot.ProjectFolderMetric
import com.github.mydogtom.talaiot.AndroidStudioMetric
talaiot {
    metrics.default()
    metrics.performance()
    metrics.metrics.add(new GitBranchMetric())
    metrics.metrics.add(new ProjectFolderMetric())
    metrics.metrics.add(new AndroidStudioMetric())

    publishers {
        ....
    }
}
```
Pay attention that in this case you have to specify all metrics manually.
You can find an example here https://github.com/MyDogTom/ConfigureTalaiot
I also tried to give more details in that article: https://medium.com/@mydogtom/explore-talaiot-plugin-configure-metrics-5ef3ae9a8c5d

**Comment by mokkun** [comment]
Hi @MyDogTom,
Thanks for the sample and references. I've ended up doing what you suggested but felt it was a bit hacky.

The syntax `metrics.metrics.add(...)` feels weird to me, and maybe it would be nicer to have a proper method for it without exposing the mutable `metrics` list. Or at least change the naming to make clear that `metrics.metrics` means `MetricsConfiguration.MetricsMutableList`.

Does it make sense?

**Comment by cdsap** [comment]
@MyDogTom this is an awesome article, thanks!

@mokkun I'm working in the unification of the metrics provider in #158, later I can address this issue. But if you or @MyDogTom have any suggestion, feel free to reach out

**Comment by MyDogTom** [comment]
one addition to that. In Groovy I could do like that
```Groovy
metrics {
    performance()
    git()
}
```
but I cannot do 
```Groovy
metrics {
    default()
}
```
I'm not sure why. I guess the name `default` overlaps with an existing Groovy function or a function generated by Gradle.
Would be nice to rename it as well.

**Comment by mokkun** [comment]
@cdsap I have some time this week and would like to give this one a go if that's okay. :)

**Comment by cdsap** [comment]
sure @mokkun 
thanks!

**Comment by mokkun** [comment]
@MyDogTom 
> I'm not sure why. I guess the name default overlaps with an existing Groovy function or a function generated by Gradle.

I think you are right. Other names I can think of are `common()`, `basic()` or `standard()`, but not sure. :thinking:

**Comment by MyDogTom** [comment]
I'd actually go with something more verbose but also more self explaining. Like: `enableStandardMetrics`, `enablePerformanceMetrics`, `enableGitMetrics` etc.

**Comment by mokkun** [comment]
@cdsap @MyDogTom I've added a PR with a proposal. https://github.com/cdsap/Talaiot/pull/162

**Comment by mokkun** [comment]
> I'd actually go with something more verbose but also more self explaining. Like: `enableStandardMetrics`, `enablePerformanceMetrics`, `enableGitMetrics` etc.

I'd just avoid using the word `enable`, making it `defaultMetrics`, `performanceMetrics` and so on instead. Reason being, we are not enabling/disabling the metrics, we are adding/removing them. That's my interpretation of it at least. :thinking:
