### ISSUE TITLE
Version 1.2.0 is not available

### ISSUE THREAD

**Issue by MyDogTom** [cdsap/Talaiot#159]
According to https://bintray.com/cdsap/maven/talaiot the latest available version is 1.1.0.  Version bump in my project also fails. Was there something wrong with the latest release?

**Comment by tinder-inakivillar** [comment]
Hi @MyDogTom 
`1.2.0` contains the change of the plugin to be deployed in the Gradle Plugin Portal. 
It also includes the change, following the convention recommended by Gradle,  the naming of the Plugin: `com.cdsap.talaiot`
Do you think I should provide a couple of versions more with Bintray?
It's not a problem for me to update it again to Bintray

Another question, when I publish the releases I post a tweet, I don't know if your account is the same as the name in GH. In the last release, I just included your name, not account:
https://twitter.com/inyaki_mwc/status/1238911229948604416?s=20

**Comment by cdsap** [comment]
btw this is the recommended conf:

## Kotlin

Using the plugins DSL
```
plugins {
  id("com.cdsap.talaiot") version "1.2.0"
}
```

Using legacy plugin application:

```
buildscript {
  repositories {
    maven {
      url = uri("https://plugins.gradle.org/m2/")
    }
  }
  dependencies {
    classpath("com.cdsap:talaiot:1.2.0")
  }
}

apply(plugin = "com.cdsap.talaiot")
```
### Groovy

Using the plugins DSL:
```
plugins {
  id "com.cdsap.talaiot" version "1.2.0"
}
```

Using legacy plugin application:
```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "com.cdsap:talaiot:1.2.0"
  }
}

apply plugin: "com.cdsap.talaiot"
```

**Comment by MyDogTom** [comment]
Thank you! With `maven { url "https://plugins.gradle.org/m2/"  }` and `apply plugin: "com.cdsap.talaiot"` everything works.

>when I publish the releases I post a tweet, I don't know if your account is the same as the name in GH.

My account is `@schatchenko`.
