### ISSUE TITLE
Discussion DSL Metrics

### ISSUE THREAD

**Issue by cdsap** [cdsap/Talaiot#168]
In https://github.com/cdsap/Talaiot/pull/167 @MyDogTom commented:

> Customising which metrics are executed might be very confusing. For example, the following
> ```
> talaiot {
>   metrics {
>     customMetrics(new MyMetric())
>   }
> }
> ```
> will disable all metrics and use only MyMetric, because standard set of metrics is used only when there is no custom configuration. This might be not what people expect and not useful if I just want to add something on top of the standard configuration.
> Similar issue with the following configuration
> ```
> talaiot {
>   metrics {
>     gitMetrics()
>   }
> }
> ```
> From the DSL it's not obvious what is actually happening.

It's a very valid point. 
This issue is to discuss how we can offer a better approach for customizing metrics

**Comment by MyDogTom** [comment]
I propose the following DSL
```groovy
talaiot {
    metrics {
        defaultMetrics = true // default is true
        gitMetrics = true // default is true
        environmentMetrics = true // default is true
        performanceMetrics = true // default is true
        gradleSwitchesMetrics = true // default is true
        customMetrics(
                new MyMetricA(),
                new MyMetricsB()
        )
    }
}
```
Like that built-in metrics are disabled only when it's explicitly specified. I believe this should eliminate possibility for confusion while keeping the same flexibility level.

**Comment by mokkun** [comment]
I like @MyDogTom's proposal, and it also matches our current DSL for publishers:

```kotlin
publishers {
    timelinePublisher = true
    taskDependencyGraphPublisher {
        html = true
        gexf = true
    }
    influxDbPublisher {
        dbName = "tracking"
        url = "http://localhost:8086"
        taskMetricName = "task"
        buildMetricName = "build"
    }
    customPublisher = CustomPublisher()
}
```

**Comment by cdsap** [comment]
got it, what would  the expectation when we have:
```
talaiot {
    metrics {
    }
}
```
or 
```
talaiot {
   publishers{
  }
}
```

**Comment by MyDogTom** [comment]
In both cases expectation is that standard set of metrics is used since the user did not change any metrics configuration.

**Comment by cdsap** [comment]
ok, perfect, can we create a new task to implement the new proposal?

**Comment by MyDogTom** [comment]
> can we create a new task to implement the new proposal?

Do you mean "issue"? For me it's fine to use current issue for the implementation as well. Actually I opened a PR with an implementation: #175

**Comment by cdsap** [comment]
yep, you're right.
 I merged the PR.
