### ISSUE TITLE
Proposal: allow more than one custom Publisher

### ISSUE THREAD

**Issue by mokkun** [cdsap/Talaiot#170]
Our current DSL only allows a single custom Publisher:

```kotlin
publishers {
    customPublisher = CustomPublisher()
}
```

I'd like to propose that we implement a similar solution to the one used for custom metrics. Something like:

```kotlin
customPublishers(
    CustomPublisher(),
    AnotherCustomPublisher()
)
```

**Comment by cdsap** [comment]
Ok, it makes sense.
