### ISSUE TITLE
Prepare Release 1.3.0

### ISSUE THREAD

**Issue by cdsap** [cdsap/Talaiot#174]
Once we confirm #171  we need to create a new release with the latest PRs.
Tasks included in the milestone 2.0.0 are not included in this PR

**Comment by cdsap** [comment]
question, do we want to include the task generated after the discussion in #168 in the release?

**Comment by MyDogTom** [comment]
I'd include #168 since it's another breaking change. Same as #167. 

Btw, I think next release deserves a migration guide explaining how metrics configuration should be adjusted.

**Comment by cdsap** [comment]
in that case, maybe we should bump to 1.3.0. What do you think?

> Btw, I think next release deserves a migration guide explaining how metrics configuration should be adjusted.
I can work on that this week

**Comment by MyDogTom** [comment]
I agree. 1.3.0 is better.

**Comment by cdsap** [comment]
being very busy this week(AS performance is decreasing), still preparing the migration lines

**Comment by mokkun** [comment]
@cdsap @MyDogTom do you think we can include https://github.com/cdsap/Talaiot/issues/170 in this release as well? I can do some work on it this week and hopefully have something ready for review until next week?

**Comment by MyDogTom** [comment]
I agree. It would be logical to include this change in release to be consistent with other DSL changes.

**Comment by cdsap** [comment]
@mokkun let me know if I can help in the #170

**Comment by MyDogTom** [comment]
I'm closing since [1.3.0](https://github.com/cdsap/Talaiot/releases/tag/1.3.0) is released.
