### ISSUE TITLE
Critical path computation question

### ISSUE THREAD

**Issue by horseunnamed** [cdsap/Talaiot#184]
Hi. In `ExecutionReport` I [found](https://github.com/cdsap/Talaiot/blob/52013d0b8b50d92f42b283246f0ffa8b2acdc9e4/talaiot/src/main/kotlin/com/cdsap/talaiot/entities/ExecutionReport.kt#L56) method that estimates critical path of build. I think that this estimation is working well on builds with high count of workers. But I doubt that it can always find longest tasks execution path on builds with low count of workers (that's why it's called "estimate"). 

There could be cases where Gradle first runs tasks of actual critical path and then synchronously (because of low count of workers) runs tasks from another path with lower total execution time. Estimation algorithm from Talaiot will decide that latest path is critical based on stopMs values from it's tasks while actually the first path is critical. 

**My question**: can I rely on Talaiot's critical path computation as always true representation of critical path for my builds, or my reasoning is correct and this algorithm is just approximation? 

**P.S.** 
I've also implemented custom publisher that computes critical path with longest path search algorithm based on tasks duration (not stopMs heuristic from `estimateCriticalPath` method). It publishes true critical path of build to JSON format as sequence of tasks and it's corresponding sequence of modules. This publisher can help to find the sequence of module dependencies that causes bottleneck for build time. 
Does it make sense to open PR with this publisher or is it too specific to be part of Talaiot?

**Comment by cdsap** [comment]
Hi @horseunnamed 
Thanks for the question/suggestion.
I would say the current implementation it's just an initial approximation. As you mentioned, there are more factors to consider in the calculation of better cirtical path.

I found very interesting your comment:
>There could be cases where Gradle first runs tasks of actual critical path and then synchronously (because of low count of workers) runs tasks from another path with lower total execution time

Do you have more details/resources about this?

We would be more than happy in receive a contribution for a new Publisher. I think we would need to create two different PR:
1- Updating the calculation of the critical path 
2- The new Publisher.

**Comment by cdsap** [comment]
closing this issue because the feature has been dropped in version 2.0
