### ISSUE TITLE
Talaiot not working with gradle 6.6

### ISSUE THREAD

**Issue by pavel-vasilev** [cdsap/Talaiot#200]
Hi, when i run any gradle task with enabled talaiot plugin my build fails, because talaiot use internal gradle api, that i think was removed in 6.6 version.
As quick fix for my project i can disable GradleScanLinkMetric via extension, but i think we should fix it.
To fix this problem we can add second condition so that metric will check that gradle version is between 5.0 and 6.6.
https://github.com/cdsap/Talaiot/blob/master/talaiot/src/main/kotlin/com/cdsap/talaiot/metrics/GradleScanLinkMetric.kt#L23
![Снимок экрана 2020-08-20 в 17 38 52](https://user-images.githubusercontent.com/46404556/90786268-0dde3300-e30c-11ea-8711-ab541e76bbda.png)

**Comment by cdsap** [comment]
Hi @pavel-vasilev thank you very much for the ticket, recently we have seen problems in 6.4 and it was solved this week. But we didn't check Gradle 6.6
I'm going to try to reproduce it and I let you know.

**Comment by cdsap** [comment]
hi @pavel-vasilev I deployed a new version: `1.3.5`. It contains your suggestion to check the Gradle Version and fixes the issue(#201). Thanks.

additionally I created a discussion issue to consider the future of this type of metric and the implementation: #203

**Comment by cdsap** [comment]
@pavel-vasilev can I close this issue?

**Comment by pavel-vasilev** [comment]
@cdsap ye, all works now thanks.
