### ISSUE TITLE
Collect details on time spent in Garbage Collection

### ISSUE THREAD

**Issue by notsatyarth** [cdsap/Talaiot#215]
Hi there,

Would  it make sense to   add support for also collecting the  duration that the process spends in garbage collection. Collecting that info would be similar to how it's done at https://github.com/runningcode/gradle-doctor/blob/master/doctor-plugin/src/main/java/com/osacky/doctor/internal/DirtyBeanCollector.kt#L5

**Comment by tinder-inakivillar** [comment]
hi @satyarths, thanks for the suggestion and it makes sense to include it

**Comment by cdsap** [comment]
added in #393 
included in the new release 2.0.4

**Comment by Anelkad** [comment]
hello @cdsap, why the metrics return 0.0 for gcTime, uptime, usage values?
