### ISSUE TITLE
Create Graph Publisher/Plugin

### ISSUE THREAD

**Issue by cdsap** [cdsap/Talaiot#223]

**Comment by cdsap** [comment]
@mokkun I have assigned this issue to you. If you have time of course and you want.
In the PR closing the issue #222 I will include the steps required to create the publisher/plugin and you can use as guideline

**Comment by mokkun** [comment]
Thanks, I will have a look. :+1:

**Comment by cdsap** [comment]
Hi, I have created https://github.com/cdsap/Talaiot/pull/229 for Influxdb

As a guideline you can follow:

1.  Create modules Plugin and Publisher for component. Currently the path is:
     library> plugins > NAME > NAME-plugin - NAME-publisher
     Recommended package names are:
     Plugin -> com.talaiot.plugin.NAME
     Publisher -> com.talaiot.publisher.NAME

2. Setup Modules with KTS scripts:
         publisher uses build plugin `kotlinLib`
         plugin uses build plugin `talaiotPlugin`
3. Move specific dependencies from `library/talaiot/build.gradle.kts` to  library > of the publisher to Gradle conf in the NAME > NAME-publisher, example:
       `implementation("org.influxdb:influxdb-java:2.19")`
4. Move required Publisher and Configurations to  NAME > NAME-publisher module
5. Move required Test Publishers to   NAME > NAME-publisher module(if the publisher requires test containers use `testImplementation(project(":library:talaiot-test-utils"))`
6. In the new plugin module define the build configuration:
```
plugins {
    id("talaiotPlugin")
}

talaiotPlugin {
    idPlugin = "com.cdsap.talaiot.plugin.NAME"
    artifact = "NAME"
    group = "com.cdsap.talaiot.plugin"
    mainClass = "com.cdsap.talaiot.plugin.influxdb.TalaiotInNAMEPlugin"
    version = "1.3.6-SNAPSHOT"
}

dependencies {
    implementation(project(":library:plugins:NAME:iNAME-publisher"))
    implementation(project(":library:talaiot"))
}
```
7- Create the required classes in the plugin:
- NAMEConfiguration.kt --> define the configuration used by the plugin. It represents the part of the configuration specific for the plugin used by legacy plugin. 
- NAMEConfigurationProvider.kt --> Adds the publisher to the conf.
- NAMEExtension.kt --> define the specific configuration for the plugin
- TalaioNAMEPlugin.kt

8- Update Hybrid Publisher with the new Publisher.(*this is not required for plugins like graph*)
    
9- Update `library/plugins/talaiot-legacy/build.gradle.kts` with the new publisher

Please, let me know if you have questions/suggestions
