### ISSUE TITLE
Define error message when we are using two different Talaiot plugins

### ISSUE THREAD

**Issue by cdsap** [cdsap/Talaiot#246]

**Comment by cdsap** [comment]
I tested the scenario when we have already in the classpath two different plugins:
```
buildscript {
    repositories {
       maven ( url = uri("http://oss.jfrog.org/artifactory/oss-snapshot-local") )
     }
    dependencies {
        classpath("com.cdsap.talaiot.plugin:base:1.3.6-SNAPSHOT")
        classpath("com.cdsap.talaiot.plugin:influxdb:1.3.6-SNAPSHOT")
    }
}

apply plugin: "com.cdsap.talaiot.plugin.base"
apply plugin: "com.cdsap.talaiot.plugin.influxdb"
```

The output shows an error:
```

1: Task failed with an exception.
-----------
* Where:
Build file '/Project/apk/build.gradle' line: 5

* What went wrong:
A problem occurred evaluating project ':apk'.
> Failed to apply plugin [id 'com.cdsap.talaiot.plugin.influxdb']
   > Cannot add extension with name 'talaiot', as there is an extension already registered with that name.
```

I think the message is quite clear and we don't need to have an additional logic for this release.
What do you think @mokkun ?

**Comment by mokkun** [comment]
> Cannot add extension with name 'talaiot', as there is an extension already registered with that name.

Should we use "plugin" instead of "extension"?  I think it may cause confusion since we don't seem to use this term anywhere else in the output. :thinking:

**Comment by mokkun** [comment]
One more question that comes to mind is if we should support applying different versions of the plugin. I can see someone using `graph` and `base` or `influxdb` together. :thinking:

**Comment by cdsap** [comment]
> Should we use "plugin" instead of "extension"? I think it may cause confusion since we don't seem to use this term anywhere else in the output. 🤔

The output it's the default used by Gradle. 

> One more question that comes to mind is if we should support applying different versions of the plugin. I can see someone using graph and base or influxdb together. 🤔

That's why we have the "legacy" plugin, it contains all the publishers and corresponds to the current released(1.3.5) plugin. 
This is the reason I don't like the term "legacy". It's legacy from the perspective of the pluginization, but the entity that represents is a "fat" plugin with all the functionality. It comes a better name?

**Comment by mokkun** [comment]
> The output it's the default used by Gradle.

Got it. :+1: 

> That's why we have the "legacy" plugin, it contains all the publishers and corresponds to the current released(1.3.5) plugin.

Still, I think we should consider make it possible to use two or three plugins in the future. As is now is one or all. :)

> This is the reason I don't like the term "legacy". It's legacy from the perspective of the pluginization, but the entity that represents is a "fat" plugin with all the functionality. It comes a better name?

Agreed. What about "standard"?

> a : regularly and widely used, available, or supplied
> b : well-established and very familiar
https://www.merriam-webster.com/dictionary/standard

**Comment by mokkun** [comment]
The above is only for internal naming correct? I think users should use `id "com.cdsap.talaiot"` to refer to the standard way of using the tool, and `id "id "com.cdsap.talaiot.plugins.PLUGIN_NAME"` for other specific ways.

**Comment by cdsap** [comment]
perfect, I like the name standard. Created issue https://github.com/cdsap/Talaiot/issues/252
And yes, the standard plugin is accessible by `"com.cdsap.talaiot"` and then the plugins follow the convention plugin.XXX

**Comment by cdsap** [comment]
btw I'm going to close this issue
