### ISSUE TITLE
Jcenter/Bintray migration

### ISSUE THREAD

**Issue by cdsap** [cdsap/Talaiot#269]
With Recent announcement we need to define the strategy of migration.

**Comment by Malinskiy** [comment]
1. Identify dependencies coming from jCenter/bintray
2. Verify there are issues created for dependencies to migrate away from jCenter/bintray
3. Upgrade dependencies

If you want to be super safe - use the `libs` local copy of dependencies from jCenter and remove the entry from `repositories` altogether.

The announcement has been updated with new dates after the initial one btw:
> the JCenter repository will keep serving packages for 12 months until February 1st 2022.

**Comment by cdsap** [comment]
Hi @Malinskiy, thanks, now we have the guideline. 
And what about our artifacts? 
We offer plugins under Gradle Plugin Portal but the publishers and core dependencies are in Bintray, do you have any recommendation?
thx!

**Comment by cdsap** [comment]
If you don't have concerns I'm going to migrate to Sonatype for storing our artifacts(publishers, core). The requirements are:
-- Supply Javadoc and sources
-- Sign your files with GPG/PGP
-- Sufficient and correct metadata for your projects

https://central.sonatype.org/pages/requirements.html?__hstc=31049440.331059e9c21aeb7d36e2cb8c69b8e10f.1614393786552.1614393786552.1614393786552.1&__hssc=31049440.3.1614393786555&__hsfp=1145089835

**Comment by cdsap** [comment]
Migrated!
