### ISSUE TITLE
Is there a way to shorten gradle task names to make analysis easier

### ISSUE THREAD

**Issue by bhargavms** [cdsap/Talaiot#279]
Currently the task names are long (Talaiot reports raw task), is there some way to give aliases to some tasks so that we can shorten them when reporting in `requestedTasks` tag?

**Comment by cdsap** [comment]
hi @bhargavms, it could be a good idea, not only in terms of visualization, maybe some clients want to obfuscate/lookup the tasks.
The immediate solution would be change the output in the visualization component , Grafana allow you to define rules in the visualization section.
Long term and thinking in the plugin, we can offer a mapping configuration allowing the user to define the rules. Later we will transform the tasks, once the build is finished.

What are your requirements?

**Comment by bhargavms** [comment]
well the problem is there is too much data being pushed into the `requestedTasks` tag on a daily basis, and long term retention becomes a problem, for now in terms visualization I think your idea will solve that issue for me

Thanks!

**Comment by bhargavms** [comment]
for anyone looking for an answer for this in the future, the plugin already solves this in the default config with influxDB, the "task" measurement tracks duration for each executed task individually.
