### ISSUE TITLE
Build completion gets dealy if we use talaiot and Gradle Enterprises build scan together

### ISSUE THREAD

**Issue by shailesh21** [cdsap/Talaiot#282]
**Context**
We uses talaiot plugin to capture build details and we are spiking Gradle Enterprise also. Gradle Enterprise has a flag called `publishOnBackground` to upload build scan in background. If this flag is set true then it launches a separate process to upload in the background. 

Talaiot also appends build scan url in final metrics. Since this would require for the build scan to be uploaded successfully, it could make it look like the build has not completed yet while this processing occurs (build scan being uploaded in the background) that the build has not completed successfully yet. **So all this process is causing extra 2-3 min delay in finishing build.**

**Comment by cdsap** [comment]
Hi @shailesh21, thanks for the issue. Sorry to hear that. The experience of waiting 2-3 min is unacceptable. 
Can you tell me which version are you using? 
We drop functionality for Gradle Build Scan in 1.4. Recently, we recovered the feature https://github.com/cdsap/Talaiot/pull/278/files but it's not included in a release version(only snapshots)

Wait for you answer, thanks

**Comment by shailesh21** [comment]
I am using Talaiot version 1.3.5. Let me check version 1.4 release notes. Thank you for the information.

**Comment by cdsap** [comment]
hi @shailesh21 
we have enabled again the BuildScanMetric in the new Release 1.5.0.
Please let me know if you see again the problem
