### ISSUE TITLE
Make TaskMetrics filter similar to what is provided for BuildMetrics for Influx publisher

### ISSUE THREAD

**Issue by yarolegovich** [cdsap/Talaiot#284]
Hi, the request is the same as [here](https://github.com/cdsap/Talaiot/issues/232), but for tasks, can we please add a similar filtering option?
Publishing all the properties as tags makes series cardinality skyrocket in a multi-module project, where there are lots of unique task names (due to a module name being prepended).
Also I can't imagine a case where having workerId as a tag would be a good idea.

**Comment by cdsap** [comment]
hi @yarolegovich 
Thank you very much for the ticket and the pr, I will review today
