### ISSUE TITLE
Plugin artifacts not published on Maven/Nexus

### ISSUE THREAD

**Issue by mokkun** [cdsap/Talaiot#301]
I updated my project with the latest changes from 1.5.0 and decided to change it only to use the `base` dependency instead of using `standard`.

Gradle complains about not being able to find `io.github.cdsap.talaiot.plugin:base:1.5.0`, so I went to check the [Maven](https://repo.maven.apache.org/maven2/io/github/cdsap/talaiot/)/[Nexus](https://s01.oss.sonatype.org/#nexus-search;quick~io.github.cdsap) repositories, and I also couldn't find it.

I've check out the latest changes and published the `1.5.1-SNAPSHOT` into Maven Local and all works as expected.

**Comment by cdsap** [comment]
Hi @mokkun, hope everything is going well. 
You're right. Just working in the new release and I published:
```
io.github.cdsap.talaiot.plugin:base:1.5.1,
```

Can you verify ?

**Comment by tinder-inakivillar** [comment]
Release 1.5.1 created https://github.com/cdsap/Talaiot/releases/tag/1.5.1

**Comment by mokkun** [comment]
Sorry, forgot to reply. All good 👍
