### ISSUE TITLE
Unexpected behavior in project with enabled configuration cache

### ISSUE THREAD

**Issue by PStrelchenko** [cdsap/Talaiot#313]
We want to send build metrics with `Talaiot` in our project with enabled Gradle's configuration cache. We noticed that when the project use saved configuration cache entry, `talaiot` will not send any metrics (no output from any publishers in the log). For me, it is not expected behavior =)

Maybe I've made some mistakes with `Talaiot` configuration, but I can't find where I was wrong.

I've prepared [simple example repo](https://github.com/PStrelchenko/TalaiotConfCacheExample) with this behavior.

Thanks in advance.

**Comment by cdsap** [comment]
@PStrelchenko I have some updates, the issue is we are registering a build listener in the plugin. This is incompatible with Configuration Cache. 
I've started working on the possible migration to BuildServices(the recommended way to implement it). I hope to have something ready for next week.

**Comment by MyDogTom** [comment]
Hi @cdsap , am I correct that #315 is not enough to fully support configuration cache? If yes, do you have any list of required actions to do? I'd like to understand if there is something I can help with.
