### ISSUE TITLE
Update CircleCi Docker Image

### ISSUE THREAD

**Issue by cdsap** [cdsap/Talaiot#326]
Builds in CircleCi are reporting:
```
This job is either using an Ubuntu 14.04 image, an Ubuntu 16.04 image, or the default Ubuntu 14.04-based image by 
specifying machine:true in config. These images (including the default image) [will be removed on May 31, 2022
```
Update the docker image.

Btw, do you have any thoughts for a possible migration to GHA?

**Comment by MyDogTom** [comment]
Sorry, I don't have any experience nor with CirceCI nor with GitHub Actions :(
