### ISSUE TITLE
Not able to use `influxDb2Publisher` in version `1.5.3`

### ISSUE THREAD

**Issue by rohithThammaiah** [cdsap/Talaiot#355]
Is there an issue with deployment here?

**Comment by MyDogTom** [comment]
Hey @rohithThammaiah , did you manage to make it work? If not could you please give more details?
* What's the exact error you receive?
* How you configure it?
* What do you see if you set `logger` to `info` mode?

**Comment by rohithThammaiah** [comment]
The project was failing to compile since was not able to find an instance of `influxDb2Publisher`

**Comment by MyDogTom** [comment]
I added `implementation "io.github.cdsap.talaiot.plugin:influxdb2:1.5.3` dependency in my personal project. I was able to sync the project and see `influxdb2-publisher` library added to my project.

The library also present on Maven: https://search.maven.org/artifact/io.github.cdsap.talaiot.plugin/influxdb2

@rohithThammaiah could you please show how you include `io.github.cdsap.talaiot.plugin:influxdb2:1.5.3` dependency and show the exact error stacktrace?
