### ISSUE TITLE
InfluxDbPublisher not pushing data from CircleCI

### ISSUE THREAD

**Issue by vikasraimeesho** [cdsap/Talaiot#357]
We have created a sandbox environment for influx db and data are pushed perfectly fine in local build but when build is ran on the CircleCI I'm not seeing the data in influxDb.

Things I have checked 
1. username and password are same in both builds
2. Logs are printing I don't see any error in circleCI 

CI Build Logs
```
[InfluxDbPublisher]: ================
[InfluxDbPublisher]: InfluxDbPublisher
[InfluxDbPublisher]: publishBuildMetrics: true
[InfluxDbPublisher]: publishTaskMetrics: true
[InfluxDbPublisher]: ================
BUILD SUCCESSFUL in 8m 28s
1383 actionable tasks: 1372 executed, 11 up-to-date
```

Local Build Logs

```
[InfluxDbPublisher]: ================
[InfluxDbPublisher]: InfluxDbPublisher
BUILD SUCCESSFUL in 12s
[InfluxDbPublisher]: publishBuildMetrics: true
[InfluxDbPublisher]: publishTaskMetrics: true
[InfluxDbPublisher]: ================
12 actionable tasks: 1 executed, 11 up-to-date
```
There are no errors reported in the logs. 

`Talaiot version -  1.5.3`

**Comment by MyDogTom** [comment]
@vikasraimeesho did you find a reason? If yes, could you please share it here? Just in case anyone else experiences the same.

**Comment by vikasraimeesho** [comment]
@MyDogTom Its happened because our influxDb can be connected via VPN only and in the system It was connected and on the CI it was not connected. We have disable the VPN for influxDB.
