### ISSUE TITLE
Creating Filter for the tasks candidates to be tracked

### ISSUE THREAD

**Issue by cdsap** [cdsap/Talaiot#38]
We may want to discard the track of different tasks. 
Create new Configuration entity to setup the regexp like: 

```
   filterTasks{
        whiteList{
        }
        blackList{
        }
    }
 ```  

Later, apply the filters in `TalaiotTracker`

**Comment by satyarths** [comment]
I was looking into picking this up. Would it be possible to explain the API a bit more in the following context?

- Do we need to ensure mutual exclusivity between the `whitelist` and `blacklist` . 
- Would this be based on only task names or a combination of module and task names.
- What happens to the tasks which are neither a part of the `whitelist` or `blacklist`.
- If a `whitelist` is present should all other tasks be ignored. 
- If a `blacklist` is present should all other tasks be tracked. 

If these are not thought out yet I can help in creating a spec for these. Do let me know

**Comment by cdsap** [comment]
Hi, 
thank you very much for the interest. 
Some of the questions raised are not detailed so I would appreciate if you want to create more detailed specs here.
 
One thing I have clear is the separation by different filters, for example, imagine I want to ignore some specific module and some specific pattern for tasks(*bundle), so it should be composed by different filters types and ideally how we want to combine the composition(Union, Intersection, Subtract) 

Let me know if you need more details

**Comment by satyarths** [comment]
Sounds good . I'll workout this spec and get back to you then 👍 . But just so we are on the page here, you mean something like 
```kotlin
   filterTasks{
        whiteList{
        }
        blackList{
        }
    }

   filterModules{
        whiteList{
        }
        blackList{
        }
    }
```
And these would be combined to determine the filter list?

**Comment by satyarths** [comment]
Consider a basic filter configuration that works on the specified parameter
```kotlin

filter<Type>{
    whiteList{

    }

    blackList{

    }
}

```

For tasks this can be

Q1.
```kotlin
filterTasks{
    whiteList{
        "assemble*"
    }

    blackList{
         ".*em*"
    }
}
```

In this case the task would be a part of the `whitelist` and `blacklist`  how would the filter work in this scenario


Q2.
```kotlin
filterTasks{
    whiteList{
        "assemble*"
    }
}
```
Would the task `mergeDexDebug` be included. The logical answer seems that it would be ignored.


Q3.
```kotlin
filterTasks{
    whiteList{
        "assemble*"
    }

    blackList{
         "install*"
    }
}
```
Would the task `packageDebug` be included. The logical answer here too seems that it would be ignored.

**Comment by cdsap** [comment]
hi @satyarths, sorry for the delay I'm at the I/O. 

Q1. You're right, we should encourage developers to don't fall in these situations on the doc and maybe we can throw some output during processing the build. 

Q2. Indeed, due to the whitelist only contains `*assemble*` all the other tasks that don't match the pattern should be ignored

Q3. Same here, due to the whitelist only contains `*assemble*` all the other tasks that don't match the pattern should be ignored

Thanks

**Comment by satyarths** [comment]
Hi @cdsap , 

Sure I understand . And your answers provide the clarifications I need. Thank you. Have fun at I/O 👍 

Thanks

**Comment by cdsap** [comment]
Hi, I'm back if you need to clarify more about this issue

**Comment by satyarths** [comment]
Hi @cdsap.
 I do have a few doubts surrounding the implementation. How ever I figured I'd submit a PR and then ask questions based on that. Will raise a PR sometime this weekend.

**Comment by cdsap** [comment]
sure no problem!

**Comment by satyarths** [comment]
@cdsap I've added the PR  for the same. Please have a look at #54 . Thanks :)

**Comment by cdsap** [comment]
Merged, thx
