### ISSUE TITLE
db tracking not found

### ISSUE THREAD

**Issue by LogosIntellect** [cdsap/Talaiot#48]
When I run my project, I get follow error.

> http://127.0.0.1:3003/write?db=tracking Not Found

I run docker image

**Comment by LogosIntellect** [comment]
I have specified the wrong port in the configuration. Please correct your README file

**Comment by cdsap** [comment]
Thanks for reporting, I will check it

**Comment by cdsap** [comment]
Thanks for reporting, I will check it

**Comment by cdsap** [comment]
updated

**Comment by cdsap** [comment]
can I close the issue?

**Comment by LogosIntellect** [comment]
Yes, Thanks!
