### ISSUE TITLE
Allow setting a threshold for the minimum task Execution Time

### ISSUE THREAD

**Issue by satyarths** [cdsap/Talaiot#49]
Hi there,

I was wondering if would be possible to add a `threshold` value for tasks whose output  should be uploaded.  I'm running this on a project which generates ~2200 tasks, and a lot of them take <10ms. This makes the string content to uploaded quite huge. So looking at some way of reducing it. 

This would be something similar to that implemented in the [build-time-tracker-plugin](https://github.com/passy/build-time-tracker-plugin#summaryreporter)

**Comment by cdsap** [comment]
hi @satyarths, 
thank you very much for the interest. I think is a very good idea. 
It should be configured at the level of the publisher, so at the moment it will affect the Output and InflixDb Publishers. 
This weekend and next week will work about this. 
And tomorrow I will check #38

**Comment by cdsap** [comment]
hi @satyarths can you take a look to the PR #50  please?

**Comment by satyarths** [comment]
This is done
