### ISSUE TITLE
Software visualisation

### ISSUE THREAD

**Issue by AshwinRaviraj** [cdsap/Talaiot#52]
Hi,
I believe there is a need for software visualisation tools to support the understanding of software systems. Many software visualisation tools, both open source and commercial, have been created for many languages, but no software visualisation tool has been created for the language Kotlin.

I have now however created one for my Bachelor thesis. I have used my application to visualise your project, and it shows the complexity of the project. The idea is the bigger the class or function, the more complex it is.
![Billede 06-05-2019 kl  11 54-1](https://user-images.githubusercontent.com/24268487/57218576-ee77a580-6ff5-11e9-8b39-3f9c21513a78.jpg)
If you could answer a few question for me, that would be very helpful!

To get started, can you tell me briefly about yourself?

a) What is your current occupation?
b) What about your programming background?
Do you use software visualisation tools to support tasks?
a) When was the last time you used these tools?
b) Please describe your experience with these tools.
Have you learned anything new from looking at this visualisation?
a) What did you learn?
b) Was it valuable?
Suggestions for improvement
Your help would really be appreciated.
Best,
Ashwin

**Comment by cdsap** [comment]
hi @AshwinRaviraj thanks for your comment. 
As the issues of this project have to be related to Talaiot, I'm closing this issue, feel free to contact me at my email and I will be very happy to answer.
