### ISSUE TITLE
Add config for metrics submission

### ISSUE THREAD

**Issue by tagantroy** [cdsap/Talaiot#85]
On our big project, we have a lot of tasks and if we report all of them our Influxdb cannot handle this amount of data. It would be great to have an option to disable task metric submission and report only build metric.

**Comment by cdsap** [comment]
Hi, 
you can use the `filterConfiguration` like:

```

    filter {
        modules {
            excludes = arrayOf("\\*")
        }
    }
```

and no tasks will be reported, I know is not the best way but should work now for the requirement to only submit build info. 
I will take a look

**Comment by roscrazy** [comment]
Hi @cdsap, fist, thank for the great tool. 
Secondly, I tried out your solution, but it does not work as expected. 
1. I have tried with 
`filter {
        modules {
            excludes = arrayOf("\\*")
        }
    }`
But it does not filter anything. 
As I understood, you want to exclude all of the modules. 
2. Therefore I tried:
`
filter {
        modules {
            excludes = arrayOf("(.*?)")
        }
    }
`
Look like it works, but it filtered out everything. I could not see any log for `OutputPublisher` or any data sent to influx DB.  
Possible it's an issue. Please help to take a look

**Comment by cdsap** [comment]
hi @roscrazy! Sure I'll take a look

**Comment by cdsap** [comment]
hi @roscrazy again, new snapshot published with new property in the `influxdbConfiguration`. 

Now you can set the publisher only sending build metrics adding the conf `publishOnlyBuildMetrics`: 

```
influxDbPublisher {
            dbName = "tracking2"
            url = "http://localhost:8086"
            taskMetricName = "task"
            buildMetricName = "build"
            publishOnlyBuildMetrics = true
            ...

snapshot 1.0.3-SNAPSHOT is available under http://oss.jfrog.org/artifactory/oss-snapshot-local

**Comment by roscrazy** [comment]
Hi @cdsap , thank for the fast response/update
I updated to our project

**Comment by tagantroy** [comment]
https://github.com/cdsap/Talaiot/pull/94
