### ISSUE TITLE
ElasticSearch support

### ISSUE THREAD

**Issue by tagantroy** [cdsap/Talaiot#89]
We cannot store task metrics in influxdb, because we have a lot of data.
It would be great to have integration with [ElasticSearch](https://www.elastic.co/) or [Loki](https://grafana.com/oss/loki#about)

**Comment by cdsap** [comment]
hi @tagantroy, your idea is to create a new publisher for ElasticSearck/Loki or split by type(task/build). 
I'm staring checking ES.

**Comment by tagantroy** [comment]
My idea - provide flexible configuration for published to be able to submit tasks only to elasticsearch and build to influx for example. Two settings submitBuildMetric=true/false and submitTaskMetric=true/false for each published would be nice feature.

**Comment by cdsap** [comment]
Hi, oh I like the idea!
If you don't mind I will create first the `ElasticSearchPublisher` for 1.0.4. Then I will go deeper in this hybrid configurations  with multiples publishers per entity

**Comment by cdsap** [comment]
pr created #94

**Comment by cdsap** [comment]
merged
