### ISSUE TITLE
InfluxDBException: retention policy not found: rpTalaiot

### ISSUE THREAD

**Issue by cdsap** [cdsap/Talaiot#91]
On a clean installation of InfluxDb the first time we try to report metrics we have this error:

```
Exception in thread "pool-4-thread-1" org.influxdb.InfluxDBException: retention policy not found: rpTalaiot at 

org.influxdb.InfluxDBException.buildExceptionFromErrorMessage(InfluxDBException.java:161) 

```

Once you change dbname it works.

**Comment by cdsap** [comment]
problem comes from `Bagan`. 
We were populating the database without retention. This was the poblem. Working as expected.

**Comment by emartynov** [comment]
I bumped into it today. Can you share what should I change and how to make upload passing?

**Comment by emartynov** [comment]
Oke I found it is default name of the retention. I just started docker image. How can I see influx database? Let me digg further.

**Comment by emartynov** [comment]
Oke found the database script creation - nothing special. So I'm going to the plugin source now to find retention usage.

**Comment by emartynov** [comment]
So I run next query to create retention policy `q=CREATE RETENTION POLICY rpTalaiot ON tracking DURATION 52w REPLICATION 1 DEFAULT`.

After this, I don't see log message and I see points in Graffana.
