### ISSUE TITLE
Build failed if InfluxDb unavailable 

### ISSUE THREAD

**Issue by LogosIntellect** [cdsap/Talaiot#95]
When I stoped InfluxDb, my Nginx configuration responsed 502 BAD REQUEST. My team didn't work, because their bulds crashes =(

**Comment by cdsap** [comment]
hi @LogosIntellect 
sorry to hear that. 
You can use the snapshot 1.0.3 that is catching the different exceptions:
```
maven ( url = uri("http://oss.jfrog.org/artifactory/oss-snapshot-local") )
```

And the current Snapshot:

```
classpath("com.cdsap:talaiot:1.0.3-SNAPSHOT")
```

please let me know if is helping

**Comment by cdsap** [comment]
@LogosIntellect if the solution of the snapshot solves the problem I can deploy a new hotfix version right now

**Comment by LogosIntellect** [comment]
It is solved problem! Thanks for the hotfix

**Comment by cdsap** [comment]
1.0.3 deployed and available

**Comment by LogosIntellect** [comment]
Thanks! I close issue
